# Generated by Django 5.0.6 on 2024-07-03 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_delete_customuser'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyNews',
            fields=[
                ('news_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.news')),
                ('score', models.IntegerField()),
                ('is_fishing', models.BooleanField(default=False)),
                ('is_faked', models.BooleanField(default=False)),
                ('reason', models.CharField(verbose_name=500)),
                ('is_saved', models.BooleanField(default=False)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('delete_at', models.DateField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
