# Generated by Django 5.0.6 on 2024-07-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify_news', '0002_rename_create_at_classifynews_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifynews',
            name='is_faked',
        ),
        migrations.RemoveField(
            model_name='classifynews',
            name='is_fishing',
        ),
        migrations.RemoveField(
            model_name='classifynews',
            name='is_saved',
        ),
        migrations.RemoveField(
            model_name='classifynews',
            name='user_id',
        ),
    ]
