# Generated by Django 5.0.6 on 2024-07-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify_news', '0003_remove_classifynews_is_faked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifynews',
            old_name='deleted_at',
            new_name='is_deleted',
        ),
    ]
