version: '3'

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - fakenews
    env_file:
      - .env

  backend:
    container_name: backend
    build: ./
    command: >
      sh -c "
        python manage.py makemigrations accounts && 
        python manage.py makemigrations channels && 
        python manage.py makemigrations classify_news && 
        python manage.py makemigrations feedbacks && 
        python manage.py makemigrations news && 
        python manage.py makemigrations scraped_news && 
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - fakenews

networks:
  fakenews:
    driver: bridge
