# Generated by Django 5.0.6 on 2024-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('channel', models.CharField(max_length=40)),
                ('published_date', models.DateField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('delete_at', models.DateField(null=True)),
            ],
        ),
    ]
