# Generated by Django 5.0.6 on 2024-07-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='news',
            name='delete_at',
        ),
        migrations.AddField(
            model_name='news',
            name='channel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='is_deleated',
            field=models.BooleanField(null=True),
        ),
    ]
