# Generated by Django 5.0.6 on 2024-07-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_deleted',
            new_name='is_deleated',
        ),
    ]
