# Generated by Django 5.0.6 on 2024-07-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_alter_channel_is_deleted_alter_channel_logo_and_more'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='news', to='channels.channel'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
