# Generated by Django 5.0.6 on 2024-07-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='channel',
            new_name='channel_id',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='delete_at',
        ),
        migrations.AddField(
            model_name='news',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
