# Generated by Django 5.0.6 on 2024-07-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_create_at_news_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_deleated',
            new_name='is_deleted',
        ),
    ]
