# Generated by Django 5.0.6 on 2024-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_is_deleted_news_is_deleated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='channel_id',
            field=models.IntegerField(),
        ),
    ]
