# Generated by Django 5.0.6 on 2024-07-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.TextField(default='image'),
        ),
    ]
