# Generated by Django 4.2.14 on 2024-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summarize',
            field=models.TextField(default=' '),
        ),
    ]
