# Generated by Django 4.2.14 on 2024-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_summarize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.TextField(default='image', null=True),
        ),
    ]
