# Generated by Django 4.2.14 on 2024-07-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_summarize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='summarize',
            field=models.TextField(default=''),
        ),
    ]
