# Generated by Django 5.0.6 on 2024-07-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_published_date_alter_news_summarize'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(default='a'),
        ),
    ]
