# Generated by Django 5.0.6 on 2024-07-08 13:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_rename_create_at_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
