# Generated by Django 5.0.6 on 2024-07-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('scraped_news', '0002_alter_scrapednews_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapednews',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
