# Generated by Django 5.0.6 on 2024-07-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='logo',
        ),
        migrations.AddField(
            model_name='channel',
            name='logo_url',
            field=models.URLField(default=False),
        ),
    ]
