# Generated by Django 5.0.6 on 2024-07-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_remove_channel_logo_channel_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='logo_url',
            field=models.URLField(),
        ),
    ]
