# Generated by Django 5.0.6 on 2024-07-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_alter_channel_is_deleted_alter_channel_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelscore',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
