# Generated by Django 5.0.6 on 2024-07-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_channelscore_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelscore',
            name='updated_at',
        ),
    ]
