# Generated by Django 5.0.6 on 2024-07-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_remove_channelscore_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelscore',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
