name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Save Docker image as tar
        run: |
          docker save myapp:latest -o myapp.tar

      - name: Deploy Docker image to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Save the SSH key to a file
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem

          # Sync Docker image to EC2 instance
          scp -i private_key.pem myapp.tar ${EC2_USER}@${EC2_HOST}:/home/ubuntu/

          # Run Docker commands on EC2 instance
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
            docker load -i /home/ubuntu/myapp.tar
            docker run -d --name myapp-container -p 80:80 myapp:latest
          EOF

          # Clean up the private key file
          rm private_key.pem
