name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

       - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        env:
          SERVICE_ACCOUNT_FILE_B64: ${{ secrets.SERVICE_ACCOUNT_FILE }}
        run: |
          echo "$SERVICE_ACCOUNT_FILE_B64" | base64 -d > service-account-file.json
          docker build -t myapp:latest .

      - name: Push Docker image
        run: |
          docker tag fake_news:latest dlaehddus18/fake_news:latest
          docker push dlaehddus18/fake_news:latest
