name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Run Docker container and tests
        run: |
          docker run --name myapp-container -d myapp:latest
          docker exec myapp-container python manage.py test
          docker stop myapp-container
          docker rm myapp-container
