name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t myapp:latest .
          docker save myapp:latest -o myapp.tar

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          set -e  # Exit on error

          echo "Saving SSH private key..."
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem

          echo "Testing SSH connection..."
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} "echo Connection successful"

          echo "Syncing files to EC2 instance..."
          rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" . ${EC2_USER}@${EC2_HOST}:/home/ubuntu/Backend

          echo "Transferring Docker image to EC2..."
          scp -i private_key.pem -o StrictHostKeyChecking=no myapp.tar ${EC2_USER}@${EC2_HOST}:/home/ubuntu/Backend

          echo "Running deployment script on EC2 instance..."
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} "cd /home/ubuntu/Backend && ./deploy.sh"

          echo "Cleaning up the private key file..."
          rm private_key.pem
